services:
  projecttemplatereact:
    image: projecttemplatereact
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3303:3303
    command: ["pnpm", "dev"]
